#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MOREENEMY 15
#define ID_TEX_MISC 20
#define ID_TEX_MAP 30


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPATROOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_MOVING_PLATFORM 6

#define OBJECT_TYPE_PORTAL	50


// --------------ID_SPRITE--------------

#define ID_SPRITE_MARIO 10000

// #define ID_SPRITE_BIG_MARIO 11xxx
// #define ID_SPRITE_SMALL_MARIO 12xxx
// #define ID_SPRITE_SMALL_MARIO_DIE 13001
// #define ID_SPRITE_FIRE_MARIO 13xxx
// #define ID_SPRITE_RACCOON_MARIO 14xxx



#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_ENEMY 30000
//#define ID_SPRITE_GOOMBA 3100x
//#define ID_SPRITE_KOOPATROOPA 32xxx

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)